Initial version of R-Car weston images
xen-troops/meta-xt-images pull request #1
Opened 2017-05-29 06:41 UTC by andr2000

2017-05-29 14:37 UTC, lorc requested changes

2017-05-29 14:37 UTC, lorc commented on classes/xt_quircks.bbclass
> +        return url
probably just `return` ?

2017-05-29 14:37 UTC, lorc commented on classes/xt_quircks.bbclass
> +        return url
the same. Should you return `url` there?

2017-05-29 14:37 UTC, lorc commented on classes/xt_quircks.bbclass
> +    d.setVar("SRC_URI", "")
Can't this broke some other target? E.g. there will some other `bbclass` that relies on `SRC_URI` at this stage.

2017-05-30 05:12 UTC, andr2000 commented on classes/xt_quircks.bbclass
> +        return url
ok

2017-05-30 05:13 UTC, andr2000 commented on classes/xt_quircks.bbclass
> +        return url
ok

2017-05-30 05:15 UTC, andr2000 commented on classes/xt_quircks.bbclass
> +    d.setVar("SRC_URI", "")
as per my understanding Yocto/bitbake do not use global environment, e.g. the "d" variable, which represents current execution thread own environment has no visibility to other's threads env and vise versa. Thus, I consider this safe.
What is more, this "d" variable changes do not even survive between different tasks of the same recipe.
Won't fix

2017-05-30 15:40 UTC, lorc commented
Thank you. Looks fine. 

`Reivewed-by Volodymyr Babchuk <vlad.babchuk@gmail.com>

2017-06-01 15:26 UTC, aanisov approved these changes

2017-06-02 05:12 UTC, merged