doma: Introduce XT_EXISTING_ANDROID_DIR
xen-troops/meta-xt-images pull request #200
Opened 2021-05-01 19:30 UTC by rshym

Note: Based on not yet merged branch.

2021-05-05 13:27 UTC, rshym commented
Directly depends on https://github.com/xen-troops/meta-xt-images/pull/197.
So, as result needs also
xen-troops/xt-distro#53
and 
https://github.com/xen-troops/meta-xt-prod-devel/pull/332

2021-05-06 08:08 UTC, rshym commented
Tested. Works as expected: with XT_EXISTING_ANDROID_DIR pointing to folder with android sources, domu_image_android:do_fetch() was disabled, provided sources were used and only do_compile() and do_install() were executed.

2021-05-08 16:01 UTC, rshym commented
Tested by build of prod-devel doma with variable not defined. Works as expected - sources are downloaded.

2021-05-18 15:22 UTC, iusyk requested changes

2021-05-18 15:22 UTC, iusyk commented on recipes-domu/domu-image-android/domu-image-android.bb
> +python __anonymous () {
i think, the required parameters of url must be checked in the function 'anonymous', and if parameters are not defined or have the unexpected values - stop the processing.

2021-05-19 10:09 UTC, rshym commented
This PR is based on #197 and can be considered as part of reworking of build of doma. So I will unite #197 and #200 to simplify review and maintenance.

2021-05-19 10:09 UTC, closed without merging